name: Push PR metadata

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    
    # only trigger this is the PR has been merged
    if: github.pull_request.merged == true
    
    outputs: ${{github.pull_request}}
    
    steps:
      # Runs a set of commands using the runners shell
      - name: Print metadata
      
