name: Push PR metadata

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    
    # only trigger this if the PR has been merged
#     if: github.pull_request.merged == true
    
    steps:
      # Runs a set of commands using the runners shell
      - name: Print metadata
        env:
          PR_CONTEXT: ${{ toJson(github.pull_request) }}
        run: echo "$PR_CONTEXT"
